steps:
  # 1) Install dependencies using `npm install` (not `npm ci`) to avoid lockfile mismatch errors
  - name: 'node:22'
    id: 'install-deps'
    entrypoint: 'bash'
    env:
      - 'NPM_CONFIG_CACHE=.npm'
    args:
      - '-c'
      - |
        set -e
        echo "Attempting npm ci (fallback to npm install)"
        # prefer a clean install from package-lock, fall back to install if lockfile out of sync
        npm ci --prefer-offline --no-audit --no-fund || npm install --no-audit --no-fund

  # 2) Build TypeScript to lib/
  - name: 'node:22'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Running tsc build"
        npm run build

  # 3) Deploy using gcloud. This step deploys the function named `api`.
  #    It uses environment variable $PROJECT_ID supplied by Cloud Build.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Deploying function 'api' to region asia-south1 (Gen 2)"
        # If your function name or region differ, update the command below.
        gcloud functions deploy api \
          --project="$PROJECT_ID" \
          --region=asia-south1 \
          --gen2 \
          --runtime=nodejs22 \
          --source=. \
          --trigger-http \
          --entry-point=api \
          --quiet

timeout: '1200s'

options:
  machineType: 'E2_HIGHCPU_16'

images: []

# No custom substitutions required here; project is passed at build submission time.
